version: '3'
services:
  mysql:
    restart: unless-stopped
    image: mariadb:10.4.28
    container_name: cens-db
    networks:
      - cens-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
    hostname: censdatabase
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  frontend:
    restart: unless-stopped
    image: cens-frontend
    container_name: cens-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - cens-network
    hostname: censfrontend

  backend:
    restart: unless-stopped
    image: cens-backend
    container_name: cens-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - cens-network
    volumes:
      - ./server/uploads:/app/cens/uploads
      - ./server/logs:/app/cens/logs
    hostname: censbackend
    depends_on:
      mysql:
        condition: service_healthy

  web:
    restart: unless-stopped
    image: nginx:latest
    container_name: cens-proxy
    networks:
      - cens-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/certs:/etc/nginx/certs
    hostname: proxy

networks:
  cens-network:
    driver: bridge
